# Generated by Django 5.1.5 on 2025-01-25 06:32

import cieloAdmin.models.memorial
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cieloAdmin", "0002_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="OptionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=100, verbose_name="그룹명"),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="설명"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="등록일"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
            ],
            options={
                "verbose_name": "옵션 그룹",
                "verbose_name_plural": "옵션 그룹",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "예식",
                "verbose_name_plural": "예식",
            },
        ),
        migrations.RemoveField(model_name="service", name="duration",),
        migrations.RemoveField(model_name="service", name="price",),
        migrations.AddField(
            model_name="service",
            name="base_price",
            field=models.IntegerField(default=0, verbose_name="기본 가격"),
        ),
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.CharField(default="일반", max_length=20, verbose_name="예식 유형"),
        ),
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="services/", verbose_name="대표 이미지"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="등록일"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(default="", verbose_name="설명"),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(default="", max_length=100, verbose_name="예식명"),
        ),
        migrations.CreateModel(
            name="MemorialPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                ("is_public", models.BooleanField(default=True, verbose_name="공개 여부")),
                ("is_pinned", models.BooleanField(default=False, verbose_name="상단 고정")),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="조회수"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memorial_posts",
                        to="cieloAdmin.guardian",
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "추모 게시글",
                "verbose_name_plural": "추모 게시글 목록",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MemorialImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_image",
                    imagekit.models.fields.ProcessedImageField(
                        upload_to="memorial/posts/%Y/%m/%d/original/",
                        validators=[cieloAdmin.models.memorial.validate_file_size],
                        verbose_name="원본 이미지",
                    ),
                ),
                (
                    "thumbnail",
                    imagekit.models.fields.ProcessedImageField(
                        upload_to="memorial/posts/%Y/%m/%d/thumbnails/",
                        verbose_name="썸네일",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="이미지 설명"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="정렬 순서")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="cieloAdmin.memorialpost",
                        verbose_name="게시글",
                    ),
                ),
            ],
            options={
                "verbose_name": "추모 이미지",
                "verbose_name_plural": "추모 이미지 목록",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="MemorialComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="내용")),
                ("is_public", models.BooleanField(default=True, verbose_name="공개 여부")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memorial_comments",
                        to="cieloAdmin.guardian",
                        verbose_name="작성자",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="cieloAdmin.memorialcomment",
                        verbose_name="상위 댓글",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="cieloAdmin.memorialpost",
                        verbose_name="게시글",
                    ),
                ),
            ],
            options={
                "verbose_name": "추모 댓글",
                "verbose_name_plural": "추모 댓글 목록",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MemorialSpace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="추모공간 제목")),
                (
                    "cover_image",
                    imagekit.models.fields.ProcessedImageField(
                        upload_to="memorial/covers/%Y/%m/%d/",
                        validators=[cieloAdmin.models.memorial.validate_file_size],
                        verbose_name="커버 이미지",
                    ),
                ),
                (
                    "background_music",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="memorial/bgm/%Y/%m/%d/",
                        validators=[cieloAdmin.models.memorial.validate_file_size],
                        verbose_name="배경음악",
                    ),
                ),
                ("is_public", models.BooleanField(default=True, verbose_name="공개 여부")),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="조회수"),
                ),
                ("start_date", models.DateTimeField(verbose_name="시작일")),
                (
                    "end_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="종료일"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guardian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memorial_spaces",
                        to="cieloAdmin.guardian",
                        verbose_name="보호자",
                    ),
                ),
                (
                    "pet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memorial_space",
                        to="cieloAdmin.pet",
                        verbose_name="반려동물",
                    ),
                ),
            ],
            options={
                "verbose_name": "추모공간",
                "verbose_name_plural": "추모공간 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="memorialpost",
            name="memorial_space",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="cieloAdmin.memorialspace",
                verbose_name="추모공간",
            ),
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=100, verbose_name="옵션명"),
                ),
                ("price", models.IntegerField(default=0, verbose_name="가격")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="등록일"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="cieloAdmin.optiongroup",
                        verbose_name="옵션 그룹",
                    ),
                ),
            ],
            options={
                "verbose_name": "옵션",
                "verbose_name_plural": "옵션",
                "ordering": ["group", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="service",
            name="blanket_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blanket_services",
                to="cieloAdmin.optiongroup",
                verbose_name="이불 옵션",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="coffin_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coffin_services",
                to="cieloAdmin.optiongroup",
                verbose_name="관 옵션",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="flower_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flower_services",
                to="cieloAdmin.optiongroup",
                verbose_name="생화 옵션",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="frame_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="frame_services",
                to="cieloAdmin.optiongroup",
                verbose_name="액자 세트 옵션",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="urn_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="urn_services",
                to="cieloAdmin.optiongroup",
                verbose_name="유골함 옵션",
            ),
        ),
    ]
