# Generated by Django 5.1.5 on 2025-01-25 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cieloAdmin", "0003_optiongroup_alter_service_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="blanket_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blanket_services",
                to="cieloAdmin.option",
                verbose_name="기본 이불 옵션",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="coffin_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coffin_services",
                to="cieloAdmin.option",
                verbose_name="기본 관 옵션",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="flower_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flower_services",
                to="cieloAdmin.option",
                verbose_name="기본 생화 옵션",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="frame_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="frame_services",
                to="cieloAdmin.option",
                verbose_name="기본 액자 세트 옵션",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="urn_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="urn_services",
                to="cieloAdmin.option",
                verbose_name="기본 유골함 옵션",
            ),
        ),
    ]
