# Generated by Django 5.1.5 on 2025-01-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cieloAdmin", "0004_service_blanket_option_service_coffin_option_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="service", name="blanket_group",),
        migrations.RemoveField(model_name="service", name="blanket_option",),
        migrations.RemoveField(model_name="service", name="category",),
        migrations.RemoveField(model_name="service", name="coffin_group",),
        migrations.RemoveField(model_name="service", name="coffin_option",),
        migrations.RemoveField(model_name="service", name="flower_group",),
        migrations.RemoveField(model_name="service", name="flower_option",),
        migrations.RemoveField(model_name="service", name="frame_group",),
        migrations.RemoveField(model_name="service", name="frame_option",),
        migrations.RemoveField(model_name="service", name="urn_group",),
        migrations.RemoveField(model_name="service", name="urn_option",),
        migrations.AddField(
            model_name="service",
            name="option_groups",
            field=models.ManyToManyField(
                blank=True, to="cieloAdmin.optiongroup", verbose_name="옵션 그룹"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
        ),
    ]
