# Generated by Django 5.1.5 on 2025-01-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cieloAdmin", "0005_remove_service_blanket_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="optiongroup",
            name="multiple",
            field=models.BooleanField(default=False, verbose_name="다중 선택 가능"),
        ),
        migrations.AddField(
            model_name="optiongroup",
            name="required",
            field=models.BooleanField(default=False, verbose_name="필수 여부"),
        ),
    ]
