# Generated by Django 5.1.5 on 2025-01-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cieloAdmin", "0006_optiongroup_multiple_optiongroup_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="options",
            field=models.ManyToManyField(
                blank=True, to="cieloAdmin.option", verbose_name="선택된 옵션"
            ),
        ),
    ]
