# Generated by Django 5.1.5 on 2025-01-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cieloAdmin", "0007_service_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="기본 옵션 여부"),
        ),
        migrations.AddField(
            model_name="optiongroup",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="기본 그룹 여부"),
        ),
        migrations.AddField(
            model_name="service",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="기본 서비스 여부"),
        ),
        migrations.AddField(
            model_name="service",
            name="status",
            field=models.CharField(
                choices=[("active", "활성"), ("inactive", "비활성")],
                default="active",
                max_length=20,
                verbose_name="상태",
            ),
        ),
    ]
